### ISSUE TITLE
Error 1 required positional argument  : device

### ISSUE THREAD

**Issue by al3dv2** [kijai/ComfyUI-VEnhancer#4]
Hi I have a error with the VEnhancer workflow on comfyui here's the error : 
![venhancererror](https://github.com/user-attachments/assets/c9c0de39-ab82-4670-aaf9-e4d53feb2db2)

**Comment by longzy1** [comment]
same problem

**Comment by cheezecrisp** [comment]
Same

Loading model from: D:\AI\ComfyUI_windows_portable\ComfyUI\models\venhancer\venhancer_paper-fp16.safetensors
leftover_keys <All keys matched successfully>
!!! Exception during processing !!! VideoToVideo.__init__() missing 1 required positional argument: 'device'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VEnhancer\nodes.py", line 79, in loadmodel
    self.model = VideoToVideo(generator)
                 ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VideoToVideo.__init__() missing 1 required positional argument: 'device'

**Comment by kijai** [comment]
My bad, forgot to push that fix I had already done. Updating now should help.

**Comment by al3dv2** [comment]
Thanks its works now
